### ISSUE TITLE
[Blog] GitFS setup on a master

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#109]
## Notes
- integrated with GitHub, GitLab, Azure DevOps
- does not require git to be installed on the master
- there are issues where the cache needs to be cleared if changing related configuration
- yaml can freakout about special characters in your password, just slap some quotes on there
- this will not show up in your filesystem like it traditionally does in `/srv/salt`

## cache clearing commands
Key Commands for unblocking a gitfs cache issue
```
$ salt-run cache.clear_git_lock gitfs type=update
$ salt-run fileserver.clear_cache
$ salt-run fileserver.update
```
## Master conf
Master configuration for a public repository using user auth:
```yaml
# /etc/salt/master.d/filesystem.conf

fileserver_backend:
  - gitfs

gitfs_provider: pygit2

gitfs_remotes:
  - https://github.com/terminal-labs/test-salt-fileserver.git:
    - update_interval: 10
    - base: main
    - user: alan-cugler
    - password: '[redacted]'

```
## file introspecting
To observe whats cache for minions to use here are some commands:
```bash
salt local\* slsutil.renderer salt://utility/init.sls --out=yaml
salt-run fileserver.dir_list
salt-run fileserver.file_list
salt local\* state.show_highstate --out=yaml

```
## Caching
when the master caches the git repository, its only recording the meta data mapping of the files. The files themselves arent pulled down until called upon by a salt command.
```bash
root@ip-172-31-4-59:/var/cache/salt/master/gitfs/refs/base# ls
top.sls  utility
root@ip-172-31-4-59:/var/cache/salt/master/gitfs/refs/base/utility# salt local\* slsutil.renderer salt://log/init.sls --out=yaml
local:
  [redacted because not the point]
root@ip-172-31-4-59:/var/cache/salt/master/gitfs/refs/base# ls
log  top.sls  utility
```
