### ISSUE TITLE
[BLOG] Runtime rendering

### ISSUE THREAD

**Issue by jtraub91** [terminal-labs/tl_web#111]
It is sometimes difficult in [salt](https://github.com/saltstack/salt) to use the result from one state to influence the logic for a follow-up state, from within a single highstate execution. [Requisites](https://docs.saltproject.io/en/latest/ref/states/requisites.html), [slots](https://docs.saltproject.io/en/latest/topics/slots/index.html), and [thorium](https://docs.saltproject.io/en/latest/topics/thorium/index.html), offer some capability in this regard, but are quite limited in the general scope of this problem.

@nixjdm offered a proposal in https://github.com/saltstack/salt-enhancement-proposals/pull/22 which suggested to allow for optionally "delaying" parts of the highstate's jinja rendering, to allow for rendering logic to be based on a previously executed result.

Another solution is found in https://github.com/saltstack/salt-enhancement-proposals/pull/33, proposing a functionality similar to [ansible](https://github.com/ansible/ansible)'s [registering [of] variables](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#registering-variables) at runtime. 

_However_, since there exists the ability to template with [file.managed](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed) and [cmd.run](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.run) (among others), and __these get evaluated at runtime__, it is actually possible, in theory, to solve many of these problems, without any additional technology added in salt. I refer to this capability as _runtime rendering_.

Consider the following example.

```
generate_a_random_number_at_runtime:
  cmd.run:
    - name: shuf -i 0-999 -n1 > /tmp/random-number

{% raw -%}
use_runtime_random_number_to_create_a_directory:
  cmd.run:
    - name: mkdir -p /tmp/random-dirs/{{ salt.cmd.run("cat /tmp/random-number") }}
    - template: jinja
{%- endraw %}
```

The "raw" jinja tags are one way to bypass salt's default sls jinja pre-rendering; in this case, allowing jinja to be passed to `cmd.run` to be evaluated later, at runtime. This allows us to fetch the result of the prior execution and use it to create a subdirectory of the same value. This seems very powerful and may open up many possible applications.
