### ISSUE TITLE
[Blog] auto accepting keys on the master

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#84]
## Topics to Cover
- Setting up a reactor to accept minion pending keys
  - warn of bad actor minions being auto accepted for masters exposed to the internet
  - warn of infinite loops if the reactor is mis-coded
- Setting the master configuration `auto_accept: True`
  - warn considered insecure
- Setting up a reactor to delete minion key accepted if minion start event is empty
  - question if possible problems could arise from this?

**Comment by alan-cugler** [comment]
```yaml
# /etc/salt/master.d/auth_reactor.conf

reactor:
  - 'salt/auth':
    - /srv/salt/reactor/auth_reactor.sls
```

```yaml
# /srv/salt/reactor/auth_reactor.sls

{% if data['act'] == 'pend' %}
Accept_new_minion:
  wheel.key.accept:
    - match: {{ data['id'] }}
{% endif %}
```
