### ISSUE TITLE
[Blog] argue for salt standard directory structure

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#85]
Argue for the inconsistency of the many salt directories and their systems.

example master configuration file to alleviate the confusion:
```yaml
# /etc/salt/master.d/filesystem.conf

file_roots:
  base:
    - /srv/salt/state
    - /srv/salt/reactor
    - /srv/salt/orch

pillar_roots:
  base:
    - /srv/salt/pillar
    - /srv/salt/beacon
    - /srv/salt/proxy
```
