### ISSUE TITLE
[Blog] How to statefully restart a minion without a failed response to master

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#86]
# Overarching Idea
One of the biggest weaknesses of the salt infrastructure is its inability to seamlessly manage itself and its own configurations. This will probably be a blog series to address this with current potential solutions to various aspects around this.

## Current Focus
This is to try and address salt minion restarts. The main pain point in restarting a minion traditionally is the state.apply that was ran fails to return. One way to address this is to use a bash script to restart the minion in the background with a delay so that job returns.

**Comment by alan-cugler** [comment]
For this example, the excuse is to update the minions log level.
```yaml
# salt: /srv/salt/state/log/files/log.conf
# file: /etc/salt/minion.d/log/conf

log_level: warning
```

**Comment by alan-cugler** [comment]
We will use this bash script to restart the minion after delivering the log file configuration. @tldlauser can you suggest any improvements to this bash file?
```bash
#!/usr/bin/env bash

LOG=/var/log/salt/minion_manage.log
timestamp=$(date +%F_%T)

exec >> $LOG # redirect stdout to the LOG file
exec 2>&1 # redirect stderr to stdout ( also to the LOG file )
echo "$timestamp INFO restart_server_minion.sh begin"

echo "$timestamp INFO stopping salt-minion"
sleep 10s
systemctl stop salt-minion
sleep 10s

if leftover_stop_pids=$(ps -aux | grep salt-minion | grep root | grep -v "grep")
then
  echo "$timestamp ERROR after 'supervisorctl stop salt-minion' leftover salt-minion PIDs: $leftover_stop_pids"
  echo "$timestamp INFO killing the hung salt-minion proccesses"
  for variable in $(ps -aux | grep salt-minion | grep root | grep -v "grep" | awk '{print $2}'); do kill -9 $variable 2> /dev/null; done;
fi

if leftover_kill_pids=$(ps -aux | grep salt-minion | grep root | grep -v "grep")
then
  echo "$timestamp ERROR after kill -9 leftover salt-minion PIDs: $leftover_kill_pids"
fi

echo "$timestamp INFO starting salt-minion"
systemctl start salt-minion
sleep 10s

echo "$timestamp INFO status salt-minion"
systemctl status salt-minion
```

**Comment by alan-cugler** [comment]
The bash file and config file are delivered in the same salt state and the bash file is executed in the final state.
```yaml
# file: /srv/salt/state/log/init.sls

minion_log_warn:
  file.managed:
    - name: /etc/salt/minion.d/log.conf
    - source: salt://log/files/log.conf


restart_minion_script:
  file.managed:
    - name: /etc/salt/minion_restart.sh
    - source: salt://utility/files/minion_restart.sh
    - mode: 755
    - user: root
    - group: root
    - makedirs: True

restart_server_minion_script:
  cmd.run:
    - name: /etc/salt/minion_restart.sh
    - bg: True
```
