### ISSUE TITLE
[Blog] installing a beacon via file.managed vs beacon.present

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#87]
The beacon documentation is horrible, hence great opportunity for us to get some traffic on such an advance subject.
There are a few ways to do the installation:
- pillars (bad idea for pillar bloat)
- beacon.present salt state
- file.managed salt state + minion restart
- execution module (not for this tutorial)

**Comment by alan-cugler** [comment]
## file.managed solution

This is the beacon watching the `/etc/salt/minion.d` directory.
``` yaml
# file: /srv/salt/state/beacon/files/beacon.conf

beacons:
  watch_miniond_directory:
    - files:
        /etc/salt/minion.d/:
          mask:
            - create
    - beacon_module: inotify
```

Here is the salt state for delivering the config to the minion
```yaml
# file: /srv/salt/state/beacon/init.sls

setup_beacon_file:
  file.managed:
    - name: /etc/salt/minion.d/beacon.conf
    - source: salt://beacon/files/beacon.conf

include:
  - utility
```
Along with the restart minion utility states
```yaml
# file: /etc/salt/state/utility/init.sls

restart_minion_script:
  file.managed:
    - name: /etc/salt/minion_restart.sh
    - source: salt://utility/files/minion_restart.sh
    - mode: 755
    - user: root
    - group: root
    - makedirs: True
    - require_in:
      - restart_server_minion_script

restart_server_minion_script:
  cmd.run:
    - name: /etc/salt/minion_restart.sh
    - bg: True
    - order: last
```

Finally, by adding a conf file we get a response:
```bash
$  salt a-remote-minion cmd.run 'touch /etc/salt/minion.d/test.conf'
```
```json-slices
salt/beacon/a-remote-minion/this_is_a_watch//etc/salt/minion.d	{
    "_stamp": "2022-11-14T03:17:32.796570",
    "change": "IN_CREATE",
    "id": "A-remote-minion",
    "path": "/etc/salt/minion.d/test.conf"
}
```

**Comment by alan-cugler** [comment]
## beacon.present solution
state configuration
```yaml
# file: /srv/salt/state/beacon/present.sls

inotify_miniond_directory:
  beacon.present:
    - save: True
    - enable: True
    - files:
       /etc/salt/minion.d:
         mask:
           - create
    - beacon_module: inotify
```
Check if beacon is active
```yaml
$ salt A\* beacons.list
A-remote-minion:
    beacons:
      inotify_miniond_directory:
      - enable: true
      - files:
          /etc/salt/minion.d:
            mask:
            - create
      - beacon_module: inotify
```

Now create a test trigger and see the response.
```bash
$ salt A\* cmd.run 'touch /etc/salt/minion.d/test4.conf'
```
```yaml
salt/beacon/A-remote-minion/inotify_miniond_directory//etc/salt/minion.d	{
    "_stamp": "2022-11-14T03:35:00.796451",
    "change": "IN_CREATE",
    "id": "A-remote-minion",
    "path": "/etc/salt/minion.d/test4.conf"
}

```
