### ISSUE TITLE
[Blog] how to instruct minions to send return data for specifc states completing

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#88]
For a while now we have found times when we wished some times salt could return some salt state results before the entire `state.apply` finished. It turns out you can encode this for specific states using requisite `fire_event.`

source: https://docs.saltproject.io/en/latest/ref/states/requisites.html#fire-event-notifications

**Comment by alan-cugler** [comment]
## Example state and event data to show a working example.
set the requisite at the end of desired states. In this case I am only doing it for the first two of three states in this state file.
```yaml
# file: /srv/salt/state/log/init.sls

minion_log_warn:
  file.managed:
    - name: /etc/salt/minion.d/log.conf
    - source: salt://log/files/log.conf
    - fire_event: True

restart_minion_script:
  file.managed:
    - name: /etc/salt/minion_restart.sh
    - source: salt://utility/files/minion_restart.sh
    - mode: 755
    - user: root
    - group: root
    - makedirs: True
    - fire_event: True

restart_server_minion_script:
  cmd.run:
    - name: /etc/salt/minion_restart.sh
    - bg: True
```
Then by watching on `salt-run state.event pretty=true` we see those results sent back with state name specific tags
```json-slices
salt/state_result/20221114034554178982/local-minion//etc/salt/minion.d/log.conf	{
    "_stamp": "2022-11-14T03:45:54.514964",
    "cmd": "_minion_event",
    "data": {
        "ret": {
            "__id__": "minion_log_warn",
            "__run_num__": 0,
            "__sls__": "log",
            "changes": {},
            "comment": "File /etc/salt/minion.d/log.conf is in the correct state",
            "duration": 44.342,
            "name": "/etc/salt/minion.d/log.conf",
            "result": true,
            "start_time": "03:45:54.459025"
        }
    },
    "id": "local-minion",
    "jid": "20221114034554178982",
    "tag": "salt/state_result/20221114034554178982/local-minion//etc/salt/minion.d/log.conf"
}
salt/state_result/20221114034554178982/local-minion//etc/salt/minion_restart.sh	{
    "_stamp": "2022-11-14T03:45:54.552704",
    "cmd": "_minion_event",
    "data": {
        "ret": {
            "__id__": "restart_minion_script",
            "__run_num__": 1,
            "__sls__": "log",
            "changes": {
                "diff": "--- \n+++ \n@@ -1,5 +1,6 @@\n #!/usr/bin/env bash\n \n+echo \"Starting salt-minion restart procedures\"\n LOG=/var/log/salt/minion_manage.log\n timestamp=$(date +%F_%T)\n \n"
            },
            "comment": "File /etc/salt/minion_restart.sh updated",
            "duration": 21.353,
            "name": "/etc/salt/minion_restart.sh",
            "result": true,
            "start_time": "03:45:54.519540"
        }
    },
    "id": "local-minion",
    "jid": "20221114034554178982",
    "tag": "salt/state_result/20221114034554178982/local-minion//etc/salt/minion_restart.sh"
}
```
