### ISSUE TITLE
[Blog] Using salt yaml state inheritance

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#89]
## salt state inheritance without jinja
There are some cons and pros to this method, but its definitely less code than doing it with jinja templates.

source: https://docs.saltproject.io/en/latest/ref/states/include.html

**Comment by alan-cugler** [comment]
## Demonstration

using the beacons states to demonstrate salt state inheritance of the utility states.
```yaml
# file: /srv/salt/state/beacon/init.sls

setup_beacon_file:
  file.managed:
    - name: /etc/salt/minion.d/beacon.conf
    - source: salt://beacon/files/beacon.conf

include:
  - utility
```
which is inheriting:
``` yaml
# file: /etc/salt/state/utility/init.sls

restart_minion_script:
  file.managed:
    - name: /etc/salt/minion_restart.sh
    - source: salt://utility/files/minion_restart.sh
    - mode: 755
    - user: root
    - group: root
    - makedirs: True
    - require_in:
      - restart_server_minion_script

restart_server_minion_script:
  cmd.run:
    - name: /etc/salt/minion_restart.sh
    - bg: True
    - order: last
```

When rendered together:
```bash
$ salt local-minion state.show_sls beacon --out=yaml
```
```yaml
local-minion:
  restart_minion_script:
    __env__: base
    __sls__: utility
    file:
    - name: /etc/salt/minion_restart.sh
    - source: salt://utility/files/minion_restart.sh
    - mode: 755
    - user: root
    - group: root
    - makedirs: true
    - require_in:
      - restart_server_minion_script
    - managed
    - order: 10000
  restart_server_minion_script:
    __env__: base
    __sls__: utility
    cmd:
    - name: /etc/salt/minion_restart.sh
    - bg: true
    - order: last
    - run
  setup_beacon_file:
    __env__: base
    __sls__: beacon
    file:
    - name: /etc/salt/minion.d/beacon.conf
    - source: salt://beacon/files/beacon.conf
    - managed
    - order: 10001
```

when ran as is:
```bash
$ salt local-minion state.apply beacon
```
```yaml
local-minion:
----------
          ID: restart_minion_script
    Function: file.managed
        Name: /etc/salt/minion_restart.sh
      Result: True
     Comment: File /etc/salt/minion_restart.sh is in the correct state
     Started: 04:04:37.411181
    Duration: 24.506 ms
     Changes:   
----------
          ID: setup_beacon_file
    Function: file.managed
        Name: /etc/salt/minion.d/beacon.conf
      Result: True
     Comment: File /etc/salt/minion.d/beacon.conf updated
     Started: 04:04:37.435867
    Duration: 18.329 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: restart_server_minion_script
    Function: cmd.run
        Name: /etc/salt/minion_restart.sh
      Result: True
     Comment: Command "/etc/salt/minion_restart.sh" run
     Started: 04:04:37.455427
    Duration: 6.55 ms
     Changes:   
              ----------
              pid:
                  187577
              retcode:
                  None
              stderr:
              stdout:

Summary for local-minion
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time:  49.385 ms
```
