### ISSUE TITLE
[Blog] beacon module enable/disable vs enable_beacon/disable_beacon

### ISSUE THREAD

**Issue by alan-cugler** [terminal-labs/tl_web#98]
facts:
- enable and disable are turn on and off the entire beacon system on a minion
- enable_beacon only works if the global enable is set to `True`
  - most likely this is a bug as there is no purpose to this flag if the global enable must always be set to true for this to work.
- disable_beacon works individually even if global enable is set to `True`

**Comment by alan-cugler** [comment]
globally set to `enable:true` and locally the inotify beacon is off, therefore the nginx beacon will run and inotify will not.

```yaml
A-remote-minion:
    beacons:
      enabled: true
      nginx_service_beacon:
      - interval: 5
      - services:
          nginx: {}
      - beacon_module: service
      this_is_a_watch:
      - files:
          /etc/salt/minion.d/:
            mask:
            - create
      - beacon_module: inotify
      - enabled: false
```

**Comment by alan-cugler** [comment]
globally set to `enable:false` and locally set to true for inotfy beacon. so nginx will not run but neither does inotify despit locally being set to `enable:true`
```yaml
A-remote-minion:
    beacons:
      enabled: false
      nginx_service_beacon:
      - interval: 5
      - services:
          nginx: {}
      - beacon_module: service
      this_is_a_watch:
      - files:
          /etc/salt/minion.d/:
            mask:
            - create
      - beacon_module: inotify
      - enabled: true
```
